### PR TITLE
add: proper executable

### LINKED ISSUE #12: Add a proper executable
running the command
```bash
 node jaksel-interpreter.js ./example/example2.jaksel
```

is a pretty long command, and i thought isn't it would be nice if we can execute it like this
```bash
jaksel ./example/example2.jaksel
```

### PR DESCRIPTION
**Pull request by reacto11mecha**
Closes #12 

This pull request contains a feature that can run on the command line when you run `jaksel <filename>`. Just run the npm install command at the root of the project as a global package.
```sh
npm i -g .
```

And to remove just run this command

```sh
npm rm -g jaksel-language
```

### CODE REVIEW

**Comment by fzn0x** [comment]
Take a note to @RioChndr just in case this PR was missing to run `npm publish` if this PR is merged.

**Comment by RioChndr** [comment]
Love it, thanks for contribution. I should publish it to npm, right ?

**Comment by reacto11mecha** [comment]
> Love it, thanks for contribution. I should publish it to npm, right ?

It's up to you, but if you want to publish it, the package name is `jaksel-language`, not the `jaksel`. Still, the way to run this program is as mentioned before.

**Comment by RioChndr** [comment]
Ok, i will check it later, so far run smoothly. And I will publish to npm too. Feel like something missing if not.

**Pull request merged**
