### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by reacto11mecha**
This pull request is just refactoring code and a little bit of a change. I think we should refactor the code before getting bigger and more complicated. It provides better readability and maintainability.

### CODE REVIEW

**Comment by RioChndr** [comment]
Thank your for refactor this project.🤩🤩 Love it

**Comment by RioChndr** [comment]
I got error when run this command

```
> node jaksel-interpreter.js example/example2.jaksel 
undefined:5
let isHidup = positive vibes;
                       ^^^^^

SyntaxError: Unexpected identifier
```

Looks like function `valueTransform` failed to transform boolean value

**Comment by reacto11mecha** [comment]
Okay i will fix it after school, thank you for detecting this problem

**Comment by reacto11mecha** [comment]
I have fixed this problem, now it should be working as intended

**Comment by RioChndr** [comment]
thank you so much for your hard working. This is very usefull

**Pull request merged**
