### PR TITLE
feature: add procedure syntax and example

### PR DESCRIPTION
**Pull request by RayhanHamada**
This pr should add procedure for reusable code invocations. also add some example

btw, awesome side project sir hehe.

### CODE REVIEW

**Comment by RioChndr** [comment]
Thank you for PR, I love it. hahaha. Looks like We should add parameter too

**Comment by RayhanHamada** [comment]
Agreed. Gonna work on it if i had time this evening. This looks interesting.

**Comment by RioChndr** [comment]
thank you very much 👍

Can't wait to merge this PR

**Comment by RayhanHamada** [comment]
Already add basic function feature. However, for the parameter currently it can only accepts variables and number literals, and native boolean (true/false, excluding "worth it" or "positive vibes", etc). For other literals like string literal currently is not supported, as it need more complex regex pattern to handles them.

**Comment by RioChndr** [comment]
Nice, good job bro. This is the first procedure concept on this language. Thank your for contribution 👍👍

**Pull request merged**
